/*
CREATE TABLE CLIENT_MASTER (
			CLIENTNO VARCHAR(6) PRIMARY KEY 
            NAME VARCHAR(20)  NOT NULL,
            ADDRESS1 VARCHAR(30),
            ADDRESS2 VARCHAR(30),
            CITY VARCHAR(30),
            PINCODE INT (6),
            STATE VARCHAR (30),
            BALDUE DOUBLE (10,2)
);
ALTER TABLE PRODUCT_MASTER
MODIFY COLUMN PRODUCTNO VARCHAR(10) PRIMARY KEY

SELECT * FROM salesman_master;

ALTER TABLE SALESMAN_MASTER 
MODIFY SALAMT DOUBLE(10,2) NOT NULL; */

/*CREATE TABLE SALES_ORDER(
			 ORDERNO VARCHAR(6) PRIMARY KEY,
             CLIENTNO VARCHAR(6) REFERENCES CLIENT_MASTER(CLIENTNO),
             ORDERDATE DATE NOT NULL,
             DELYADDR VARCHAR(25),
             SALESMANNO VARCHAR(6) REFERENCES SALESMAN_MASTER(SALESMANNO),
             DELYTYPE CHAR(1),
             BILLYN CHAR(1),
             DELYDATE DATE
); */
SELECT* FROM CLIENT_MASTER;
SELECT * FROM PRODUCT_MASTER;

SELECT NAME, CITY, STATE FROM CLIENT_MASTER 
WHERE STATE != 'Maharashtra';


SELECT DESCRIPTION FROM PRODUCT_MASTER
WHERE QTYONHAND > 'REORDERLVL';

SELECT * FROM PRODUCT_MASTER

SELECT DISTINCT  DESCRIPTION FROM PRODUCT_MASTER;

SHOW TABLES;
SHOW DATABASES;

SELECT AVG(COSTPRICE) FROM PRODUCT_MASTER;

SELECT * FROM PRODUCT_MASTER;

SELECT PRODUCTNO, AVG(PROFITPERCENT) FROM PRODUCT_MASTER
GROUP BY PRODUCTNO;
SELECT * FROM EMP_MSTR;

INSERT INTO EMP_MSTR (EMP_NO, BRANCH_NO)
					  VALUES ('B1', 2);
INSERT INTO EMP_MSTR (EMP_NO, BRANCH_NO)
					VALUES('B2',2);
INSERT INTO EMP_MSTR (EMP_NO, BRANCH_NO)
					VALUES('B3',2);
                    
 INSERT INTO EMP_MSTR (EMP_NO, BRANCH_NO)
					VALUES('B4',2);                   
	ALTER TABLE EMP_MSTR
    MODIFY EMP_NO VARCHAR(6);

UPDATE EMP_MSTR
SET EMP_NO = 'B1'
WHERE EMP_NO = 2;

SHOW TABLES;

CREATE TABLE ACCT_MSTR(VERI_EMP_NO VARCHAR(10),ACCT_NO VARCHAR(10)) ;

INSERT INTO ACCT_MSTR (VERI_EMP_NO, ACCT_NO)
VALUES (E1);

SELECT* 
FROM CLIENT_MASTER;

SELECT CITY, AVG(BALDUE) FROM CLIENT_MASTER
GROUP BY CITY;

SELECT * FROM SALESMAN_MASTER;

SELECT ADDRESS1 "FULL", ADDRESS2 "ADDRESS" FROM SALESMAN_MASTER 
WHERE SALESMANNAME = 'AMAN';

SELECT ADDRESS1 "FULL", ADDRESS2 "ADDRESS", CITY "OF", PINCODE "CUSTOMER", STATE FROM SALESMAN_MASTER
WHERE CLIENTNO IN(SELECT CLIENTNO FROM CLIENT_MASTER
WHERE NAME = "IVAN BAYROSS");

/* Exercise */

SELECT * FROM CLIENT_MASTER;
SELECT NAME FROM CLIENT_MASTER;

SELECT NAME, CITY, STATE FROM CLIENT_MASTER;

SELECT DESCRIPTION FROM PRODUCT_MASTER;

SELECT CLIENTNO, NAME FROM CLIENT_MASTER
WHERE CITY = 'Mumbai';

select * from salesman_master;

Select salesmanname from salesman_master
where salamt = '3000';

4

a). UPDATE CLIENT_MASTER
SET CITY = "BANGALORE"
WHERE CLIENTNO = 'C00005';

b.)
UPDATE CLIENT_MASTER
SET BALDUE = '1000'
WHERE CLIENTNO = "C00001";

SELECT * FROM PRODUCT_MASTER;
c).
UPDATE PRODUCT_MASTER
SET COSTPRICE= '950'
WHERE DESCRIPTION = "TROUSERS";

d.) SELECT * FROM SALESMAN_MASTER;

UPDATE client_MASTER
SET CITY = 'Pune';


6. 
SELECT* FROM CLIENT_MASTER;
a.)
ALTER TABLE CLIENT_MASTER
ADD (TELEPHONE INT(12));

b.) SELECT * FROM PRODUCT_MASTER

ALTER TABLE PRODUCT_MASTER
MODIFY (SELLPRICE number(10,2));

PART III

a.)
SELECT NAME FROM CLIENT_MASTER
WHERE NAME LIKE '_A%';

b.)
SELECT NAME FROM CLIENT_MASTER
WHERE CITY LIKE 'M%';

C.)
SELECT NAME, clientNo FRoM CLIENT_MASTER
WHERE CITY IN('Bangalore', 'Managalore')  /* Here we used clause IN to fetch the both cities's client name and clientNo. */

d.)

SELECT NAME, CLIENTNO, BALDUE FROM CLIENT_MASTER
WHERE BALDUE > '1000';

SELECT * FROM product_master

f.)
Select * from CLIENT_MASTER
WHERE CLIENTNO IN('C00001', 'C00002');

g) 
SELECT PRODUCTNO, DESCRIPTION FROM PRODUCT_MASTER
WHERE SELLPRICE >'500'AND SELLPRICE <'750';

h)
SELECT PRODUCTNO, DESCRIPTION, SELLPRICE*.15 "new selling price", COSTPRICE*2 "NEW COST PRICE" FROM PRODUCT_MASTER
WHERE SELLPRICE >'500';
select * from CLIENT_master

i)
SELECT NAME, CITY, STATE FROM CLIENT_MASTER
WHERE STATE != 'MAHARASHTRA';

k)
SELECT AVG(SELLPRICE) FROM PRODUCT_MASTER /* Average function */

l)
SELECT MAX(SELLPRICE) "max_price", MIN(SELLPRICE) "min_price" FROM PRODUCT_MASTER; /* We can use two functions with column in one line */

m)
SELECT COUNT(DESCRIPTION) FROM PRODUCT_MASTER
WHERE SELLPRICE <= '500';


n)
SELECT * FROM PRODUCT_MASTER
WHERE QTYONHAND < REORDERLVL;

SELECT DISTINCT COSTPRICE, SELLPRICE FROM PRODUCT_MASTER;

select costprice from product_master
where costprice = '250';
