/* CREATE TABLE CLIENT_MASTER (
			CLIENTNO varchar(6),
            NAME varchar(20),
            ADDRESS1 varchar(30),
            ADDRESS2 VARCHAR(30),
            CITY VARCHAR(15),
            PINCODE INT(8),
            STATE VARCHAR(15),
            BALDUE DOUBLE(10,2)
);
CREATE TABLE PRODUCT_MASTER
(			PRODUCTNO VARCHAR(6),
			DESCRIPTION VARCHAR(15),
            PROFITPERCENT DOUBLE(4,2),
            UNITMEASURE VARCHAR(10),
            QTYONHAND INT(8),
            REORDERLVL INT(8),
            SELLPRICE DOUBLE(8,2),
            COSTPRICE DOUBLE (8,2)
            
); 
CREATE TABLE SALESMAN_MASTER
(			SALESMANNO VARCHAR(6),
			SALESMANNAME VARCHAR(23),
            ADDRESS1 VARCHAR (30),
            ADDRESS2 VARCHAR(30),
            CITY VARCHAR(20),
            PINCODE INT(8),
            STATE VARCHAR(20),
            SALAMT DOUBLE (8,2),
            TGTTPGET DOUBLE(6,2),
            YTDSALES DOUBLE (6,2),
            REMARKS VARCHAR (60)
); */

 /*INSERT INTO CLIENT_MASTER (CLIENTNO, NAME, CITY, PINCODE, STATE, BALDUE)
			VALUES('C00001', 'Ivan Bayross', 'Mumbai', 400054, 'Maharashtra', 15000);
INSERT INTO CLIENT_MASTER (CLIENTNO, NAME, CITY, PINCODE, STATE, BALDUE)
            VALUES('C00002', 'Mamta Muzumdar','Madras', 780001, 'Tamil Nadu', 0);
INSERT INTO CLIENT_MASTER (CLIENTNO, NAME, CITY, PINCODE, STATE, BALDUE)
			VALUES('C00003', 'Chhaya Bankar', 'Mumbai', 400057, 'Maharashtra', 5000); 
INSERT INTO CLIENT_MASTER (CLIENTNO, NAME, CITY, PINCODE, STATE, BALDUE)
           VALUES('C00004', 'Ashwini Joshi', 'Banaglore', 560001, 'Karnataka', 0); 
INSERT INTO CLIENT_MASTER (CLIENTNO, NAME, CITY, PINCODE, STATE, BALDUE)
			VALUES('C00005', 'Hansel Colaco', 'Mumbai', 400060, 'Maharashtra', 2000);
INSERT INTO CLIENT_MASTER (CLIENTNO, NAME, CITY, PINCODE, STATE, BALDUE)
			VALUES('C00006', 'Deepak Sharma', 'Managalore', 560050, 'Karnataka', 0); 
            */



/*
INSERT INTO PRODUCT_MASTER(PRODUCTNO, DESCRIPTION, PROFITPERCENT, UNITMEASURE,QTYONHAND, REORDERLVL, SELLPRICE, COSTPRICE)
			VALUES('P00001', 'T-Shirts', 5, 'Piece', 200, 50, 350, 250);
INSERT INTO PRODUCT_MASTER(PRODUCTNO, DESCRIPTION, PROFITPERCENT, UNITMEASURE,QTYONHAND, REORDERLVL, SELLPRICE, COSTPRICE)
            VALUES ('P0345', 'Shirts', 6, 'Piece',150,50,500,350);
INSERT INTO PRODUCT_MASTER(PRODUCTNO, DESCRIPTION, PROFITPERCENT, UNITMEASURE,QTYONHAND, REORDERLVL, SELLPRICE, COSTPRICE)
			Values ('P06734', 'Cotton Jeans', 5, 'Piece', 100, 20,600,450);
INSERT INTO PRODUCT_MASTER(PRODUCTNO, DESCRIPTION, PROFITPERCENT, UNITMEASURE,QTYONHAND, REORDERLVL, SELLPRICE, COSTPRICE)
			VALUES('P07865', 'Jeans',5, 'Piece',100, 20, 750,500 );
INSERT INTO PRODUCT_MASTER(PRODUCTNO, DESCRIPTION, PROFITPERCENT, UNITMEASURE,QTYONHAND, REORDERLVL, SELLPRICE, COSTPRICE)
			VALUES('P07868', 'Trousers', 2, 'Piece', 150,50,850,550);
INSERT INTO PRODUCT_MASTER(PRODUCTNO, DESCRIPTION, PROFITPERCENT, UNITMEASURE,QTYONHAND, REORDERLVL, SELLPRICE, COSTPRICE)
			VALUES('P07885', 'Pull Overs', 'Piece', 80, 30, 700,450);
INSERT INTO PRODUCT_MASTER(PRODUCTNO, DESCRIPTION, PROFITPERCENT, UNITMEASURE,QTYONHAND, REORDERLVL, SELLPRICE, COSTPRICE)
			VALUES('P07965', 'Denim Shirts', 4, 'Piece', 100, 40, 350, 250);
INSERT INTO PRODUCT_MASTER(PRODUCTNO, DESCRIPTION, PROFITPERCENT, UNITMEASURE,QTYONHAND, REORDERLVL, SELLPRICE, COSTPRICE)
			VALUES('P07975', 'Lycra Tops', 5, 'Piece', 70, 30,300, 175 );
INSERT INTO PRODUCT_MASTER(PRODUCTNO, DESCRIPTION, PROFITPERCENT, UNITMEASURE,QTYONHAND, REORDERLVL, SELLPRICE, COSTPRICE)
			VALUES('P08865', 'Skirts', 5, 'Piece', 75, 30,450,300); 

*/
/*
INSERT INTO SALESMAN_MASTER(SALESMANNO, SALESMANNAME, ADDRESS1, ADDRESS2, CITY, PINCODE, STATE, SALAMT, TGTTPGET, YTDSALES, REMARKS) 
			VALUES('S0001', 'Aman', 'A/14', 'Worli', 'Mumbai', 400002, 'Maharashtra', 3000,100,50, 'Good');
INSERT INTO SALESMAN_MASTER(SALESMANNO, SALESMANNAME, ADDRESS1, ADDRESS2, CITY, PINCODE, STATE, SALAMT, TGTTPGET, YTDSALES, REMARKS)           
  			VALUES('S0002', 'Omkar', 65, 'Nariman', 'Mumbai', 400001, 'Maharashtra', 3000, 200, 100, 'Good');
INSERT INTO SALESMAN_MASTER(SALESMANNO, SALESMANNAME, ADDRESS1, ADDRESS2, CITY, PINCODE, STATE, SALAMT, TGTTPGET, YTDSALES, REMARKS) 
			VALUES('S00003', 'Raj', 'P-7', 'Bandra', 'Mumbai', 400032, 'Maharashtra', 3000, 200, 100, 'Good');
INSERT INTO SALESMAN_MASTER(SALESMANNO, SALESMANNAME, ADDRESS1, ADDRESS2, CITY, PINCODE, STATE, SALAMT, TGTTPGET, YTDSALES, REMARKS) 
			VALUES('S00004', 'Ashish', 'A/5', 'Juhu', 'Mumbai', 400044, 'Maharashtra', 3500, 200, 150, 'Good');
			
            EXERCISE:
	3
            a) SELECT NAME FROM CLIENT_MASTER
            b) SELECT * FROM CLIENT_MASTER
            c) SELECT NAME, CITY, STATE FROM CLIENT_MASTER
            d) SELECT DESCRIPTION FROM PRODUCT_MASTER
            e)	SELECT Name FROM CLIENT_MASTER
            WHERE city = 'Mumbai'
            f). Select SALESMANNAME FROM SALESMAN_MASTER
			WHERE SALAMT >'3000';
	4
			a) UPDATE CLIENT_MASTER
			 SET CITY = 'Bangalore' 
			WHERE CITY = 'MUMBAI'
            
            DIFFERENCE BETWEEN UPDATE AND ALTER
            IT'S ALWAYS ALTER (TABLE): Modifying the structure of table
            AND UPDATE (DATA): Modifying the data in table.
*/  








            
